CV/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.AboutView.as_view(), name='CV'),
    path('', views.AboutView.as_view(), name='about'),
    path('update/<int:pk>', views.AboutUpdateView.as_view(), name='about_edit'),
    path('skills/', views.SkillsView.as_view(), name='skills'),
    path('skills/update/<int:pk>', views.SkillsUpdateView.as_view(), name='skills_edit'),
    path('skills/create/', views.SkillsCreateView.as_view(), name='skills_create'),
    path('skills/delete/<int:pk>', views.SkillsDeleteView.as_view(), name='skills_delete'),
    path('interests/', views.InterestsView.as_view(), name='interests'),
    path('interests/update/<int:pk>', views.InterestsUpdateView.as_view(), name='interests_edit'),
    path('interests/create/', views.InterestsCreateView.as_view(), name='interests_create'),
    path('interests/delete/<int:pk>', views.InterestsDeleteView.as_view(), name='interests_delete'),
    path('experience/', views.ExperienceView.as_view(), name='experience'),
    path('experience/edit/<int:pk>/', views.ExperienceUpdateView.as_view(), name='experience_edit'),
    path('experience/create/', views.ExperienceCreateView.as_view(), name='experience_create'),
    path('experience/delete/<int:pk>/', views.ExperienceDeleteView.as_view(), name='experience_delete'),
    path('education/', views.EducationView.as_view(), name='education'),
    path('education/edit/<int:pk>/', views.EducationUpdateView.as_view(), name='education_edit'),
    path('education/create/', views.EducationCreateView.as_view(), name='education_create'),
    path('education/delete/<int:pk>/', views.EducationDeleteView.as_view(), name='education_delete'),
]

blog_cv/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

from Blog import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('CV/', include('CV.urls')),
    path('', include('Blog.urls')),
    path('accounts/login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name='logout', kwargs={'next_page': '/'}),
    path('accounts/profile/', views.PostListView.as_view())
]

CV/models.py
from django.db import models


# Create your models here.

class About(models.Model):
    description = models.TextField()

    def __str__(self):
        return self.description


class Experience(models.Model):
    job_title = models.TextField(max_length=256)
    job_description = models.TextField()
    job_company = models.TextField(max_length=256)
    job_start_date = models.DateField()
    job_end_date = models.DateField()

    def __str__(self):
        return self.job_title


class Education(models.Model):
    certificate_title = models.TextField(max_length=512)
    certificate_description = models.TextField()
    certificate_start_date = models.DateField()
    certificate_end_date = models.DateField()
    certificate_institute = models.TextField(max_length=256)

    def __str__(self):
        return self.certificate_title


class Skills(models.Model):
    skills_text = models.TextField()

    def __str__(self):
        return self.skills_text


class Interests(models.Model):
    interests_text = models.TextField()

    def __str__(self):
        return self.interests_text

CV/forms.py
from django import forms

from .models import About, Skills, Interests, Experience, Education


class ExperienceForm(forms.ModelForm):
    class Meta:
        model = Experience
        fields = '__all__'

        widgets = {
            'job_title': forms.TextInput(),
            'job_description': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
            'job_company': forms.TextInput(),
            'job_start_date': forms.DateInput(format='%d/%m/%Y'),
            'job_end_date': forms.DateInput(format='%d/%m/%Y'),
        }


class AboutForm(forms.ModelForm):
    class Meta:
        model = About
        fields = '__all__'

        widgets = {
            'about': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }


class SkillsForm(forms.ModelForm):
    class Meta:
        model = Skills
        fields = '__all__'

        widgets = {
            'skills': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }


class InterestsForm(forms.ModelForm):

    class Meta:
        model = Interests
        fields = '__all__'

        widgets = {
            'interests': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
        }


class EducationForm(forms.ModelForm):
    class Meta:
        model = Education
        fields = '__all__'

        widgets = {
            'certificate_title': forms.TextInput(),
            'certificate_description': forms.Textarea(attrs={'class': 'editable medium-editor-textarea'}),
            'certificate_start_date': forms.DateInput(format='%d/%m/%Y'),
            'certificate_end_date': forms.DateInput(format='%d/%m/%Y'),
            'certificate_institute': forms.TextInput(),
        }

CV/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView
from django.views.generic.edit import FormMixin, DeleteView, UpdateView

from CV.forms import ExperienceForm, EducationForm, AboutForm, SkillsForm, InterestsForm
from CV.models import About, Education, Experience, Skills, Interests


class AboutView(ListView):
    model = About

    def get_queryset(self):
        return About.objects.all()


class AboutUpdateView(LoginRequiredMixin, UpdateView, FormMixin):
    login_url = '/login/'
    redirect_field_name = 'CV/about'
    model = About
    form_class = AboutForm

    def get_context_data(self, **kwargs):
        context = super(AboutUpdateView, self).get_context_data(**kwargs)
        text = About.objects.get(pk=self.kwargs.get('pk')).description
        context['form'] = AboutForm(initial={'form': self.object, 'description': text})
        return context

    success_url = reverse_lazy('about')

class EducationView(ListView):
    model = Education

    def get_queryset(self):
        return Education.objects.order_by('-certificate_end_date')


class EducationUpdateView(LoginRequiredMixin, UpdateView, FormMixin):
    login_url = '/login/'
    redirect_field_name = 'CV/education_list'

    form_class = EducationForm

    model = Education

    def get_context_data(self, **kwargs):
        context = super(EducationUpdateView, self).get_context_data(**kwargs)
        certificate_description = Education.objects.get(pk=self.kwargs.get('pk')).certificate_description
        certificate_title = Education.objects.get(pk=self.kwargs.get('pk')).certificate_title
        certificate_institute = Education.objects.get(pk=self.kwargs.get('pk')).certificate_institute
        certificate_start_date = Education.objects.get(pk=self.kwargs.get('pk')).certificate_start_date
        certificate_end_date = Education.objects.get(pk=self.kwargs.get('pk')).certificate_end_date
        context['form'] = EducationForm(initial={'form': self.object, 'certificate_title': certificate_title,
                                                 'certificate_description': certificate_description,
                                                 'certificate_start_date': certificate_start_date,
                                                 'certificate_end_date': certificate_end_date,
                                                 'certificate_institute': certificate_institute}, )
        return context

    success_url = reverse_lazy('education')


class EducationDeleteView(LoginRequiredMixin, DeleteView):
    model = Education
    ordering = ['-job_start_date']

    success_url = reverse_lazy('education')


class EducationCreateView(LoginRequiredMixin, CreateView, FormMixin):
    login_url = '/login/'
    redirect_field_name = 'CV/education_list'

    form_class = EducationForm

    model = Education

    def get_context_data(self, **kwargs):
        context = super(EducationCreateView, self).get_context_data(**kwargs)
        context['form'] = EducationForm(initial={'form': self.object})
        return context

    success_url = reverse_lazy('education')


class ExperienceView(ListView):
    model = Experience

    def get_queryset(self):
        return Experience.objects.order_by('-job_end_date')


class ExperienceDeleteView(LoginRequiredMixin, DeleteView):
    model = Experience
    ordering = ['-job_start_date']

    success_url = reverse_lazy('experience')


class ExperienceCreateView(LoginRequiredMixin, CreateView, FormMixin):
    login_url = '/login/'
    redirect_field_name = 'CV/experience_list'

    form_class = ExperienceForm

    model = Experience

    def get_context_data(self, **kwargs):
        context = super(ExperienceCreateView, self).get_context_data(**kwargs)
        context['form'] = ExperienceForm(initial={'form': self.object})
        return context

    success_url = reverse_lazy('experience')


class ExperienceUpdateView(LoginRequiredMixin, UpdateView, FormMixin):
    login_url = '/login/'
    redirect_field_name = 'CV/experience_list'

    form_class = ExperienceForm

    model = Experience

    def get_context_data(self, **kwargs):
        context = super(ExperienceUpdateView, self).get_context_data(**kwargs)
        job_description = Experience.objects.get(pk=self.kwargs.get('pk')).job_description
        job_title = Experience.objects.get(pk=self.kwargs.get('pk')).job_title
        job_company = Experience.objects.get(pk=self.kwargs.get('pk')).job_company
        job_start_date = Experience.objects.get(pk=self.kwargs.get('pk')).job_start_date
        job_end_date = Experience.objects.get(pk=self.kwargs.get('pk')).job_end_date
        context['form'] = ExperienceForm(
            initial={'form': self.object, 'job_description': job_description, 'job_title': job_title,
                     'job_company': job_company, 'job_start_date': job_start_date, 'job_end_date': job_end_date})
        return context

    success_url = reverse_lazy('experience')


class SkillsView(ListView):
    model = Skills

    def get_queryset(self):
        return Skills.objects.all()


class SkillsDeleteView(LoginRequiredMixin, DeleteView):
    model = Skills

    def get_success_url(self):
        return reverse_lazy('skills')


class SkillsUpdateView(LoginRequiredMixin, UpdateView, FormMixin):
    login_url = '/login/'
    redirect_field_name = 'CV/skills'
    model = Skills
    form_class = SkillsForm

    def get_context_data(self, **kwargs):
        context = super(SkillsUpdateView, self).get_context_data(**kwargs)
        text = Skills.objects.get(pk=self.kwargs.get('pk')).skills_text
        context['form'] = SkillsForm(initial={'form': self.object, 'skills_text': text})
        return context

    success_url = reverse_lazy('skills')


class SkillsCreateView(LoginRequiredMixin, CreateView, FormMixin):
    login_url = '/login/'
    redirect_field_name = 'CV/skills'
    model = Skills
    form_class = SkillsForm

    def get_context_data(self, **kwargs):
        context = super(SkillsCreateView, self).get_context_data(**kwargs)
        context['form'] = SkillsForm(initial={'form': self.object})
        return context

    success_url = reverse_lazy('skills')


class InterestsView(ListView):
    model = Interests

    def get_queryset(self):
        return Interests.objects.all()


class InterestsDeleteView(LoginRequiredMixin, DeleteView):
    model = Interests
    success_url = reverse_lazy('interests')

class InterestsUpdateView(LoginRequiredMixin, UpdateView, FormMixin):
    login_url = '/login/'
    redirect_field_name = 'CV/interests'
    model = Interests
    form_class = InterestsForm

    def get_context_data(self, **kwargs):
        context = super(InterestsUpdateView, self).get_context_data(**kwargs)
        text = Interests.objects.get(pk=self.kwargs.get('pk')).interests_text
        context['form'] = InterestsForm(initial={'form': self.object, 'interests_text': text})
        return context

    success_url = reverse_lazy('interests')


class InterestsCreateView(LoginRequiredMixin, CreateView, FormMixin):
    login_url = '/login/'
    redirect_field_name = 'CV/interests'
    model = Interests
    form_class = InterestsForm

    def get_context_data(self, **kwargs):
        context = super(InterestsCreateView, self).get_context_data(**kwargs)
        context['form'] = InterestsForm(initial={'form': self.object})
        return context

    success_url = reverse_lazy('interests')

templates/CV/about_form.html
{% extends 'CV/base.html' %}

{% load crispy_forms_tags %}
{% block info %}
    <h1>Update About</h1>
    <div class="jumbotron" style="background-color: white">
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-primary" id = 'Save'>Save</button>
    </form>
    </div>
{% endblock %}

templates/CV/about_list.html
{% extends 'CV/base.html' %}
{% block info %}
    <section class="resume-section">
    <div class="resume-section-content jumbotron" style="background-color: white">
    {% if user.is_authenticated %}
        {% for about in about_list %}
        <h1 class="mb-0">Alexandru
            <span class="text-primary">Onofras</span>
        </h1>
        <div class="subheading mb-5">
            Birmingham · West Midlands ·<a href="mailto:onofrass@gmail.com">onofrass@gmail.com</a>
        </div>

        <p class="lead mb-5" id='id_about'>{{ about.description }}<a href="{% url 'about_edit' pk=about.pk %}" style="color:#212529;" id="Edit"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                                  <path fill-rule="evenodd" d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z"/>
                                                                  <path fill-rule="evenodd" d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 0 0 .5.5H4v.5a.5.5 0 0 0 .5.5H5v.5a.5.5 0 0 0 .5.5H6v-1.5a.5.5 0 0 0-.5-.5H5v-.5a.5.5 0 0 0-.5-.5H3z"/>
                                                                  </svg></a>
        </p>
            {% endfor %}
    {% else %}
        {% for about in about_list %}
        <h1 class="mb-0">Alexandru
            <span class="text-primary">Onofras</span>
        </h1>
        <div class="subheading mb-5">
            Birmingham · West Midlands ·<a href="mailto:onofrass@gmail.com">onofrass@gmail.com</a>
        </div>
        <p class="lead mb-5" id = 'id_about'>{{ about.description }}</p>
            {% endfor %}
    {% endif %}
    </div>
    </section>
{% endblock %}

templates/CV/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>CV</title>

    <!-- JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <!-- Font Awesome icons (free version)-->
    <script src="https://kit.fontawesome.com/f3f6ea2c4a.js" crossorigin="anonymous"></script>
    <script src="https://use.fontawesome.com/de44a2323f.js"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
    <!-- Bootstrap -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}" type="text/css">
    <script src="{% static 'js/bootstrap.js' %}"></script>


</head>
<body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav" style="background-color: #212529">
            <a class="navbar-brand js-scroll-trigger" href="https://www.linkedin.com/in/alex-onofras">
                <span class="d-block d-lg-none">Alexandru Onofras</span>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    {% if  not user.is_authenticated %}
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" id="login" href="{% url 'login' %}"><svg class="bi bi-person-circle" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                                                                      <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                                                                                                      <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                                                                                                      <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
                                                                                                      </svg></a> </li>
                    {% endif %}
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'CV' %}">About</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'experience' %}">Experience</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'education' %}">Education</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'skills' %}">Skills</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'interests' %}">Interests</a></li>
                    <li class="nav-item"><a class="nav-link js-scroll-trigger" id="back" href="{% url 'post_list' %}">Back</a></li>
                </ul>
            </div>
        </nav>
         <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block info %}
                    {% endblock %}
                </div>
            </div>
         </div>
</body>
</html>

templates/CV/education_confirm_delete.html
{% extends 'CV/base.html' %}
{% block info %}
    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4 mt-5">
    <div class="jumbotron jumbotron-fluid" style="background-color: white">
    <form action="" method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete the entry for "{{ education.certificate_title }}"?</p>
        <input class='btn btn-danger' type="submit" value="Confirm" id="id_confirm" />
        <a class="nav-link" href="{% url 'education' %}" id="id_cancel">Cancel</a>
    </form>
    </div>
    </div>
{% endblock %}

templates/CV/education_form.html
{% extends 'CV/base.html' %}
{% load crispy_forms_tags %}
{% block info %}
    <h1>Update Education</h1>
    <div class="jumbotron" style="background-color: white">
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-primary" id ="id_save">Save</button>
    </form>
    </div>
{% endblock %}

templates/CV/experience_confirm_delete.html
{% extends 'CV/base.html' %}
{% block info %}

    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4 mt-5">
    <div class="jumbotron jumbotron-fluid" style="background-color: white">
    <form action="" method="post" class="justify-content-center">{% csrf_token %}
        <p class="alert alert-danger">Are you sure you want to delete the entry for "{{ experience.job_title }}"?</p>
        <input class='btn btn-danger' type="submit" value="Confirm" id="id_confirm" />
        <a class="nav-link" href="{% url 'experience' %}" id="id_cancel">Cancel</a>
    </form>
    </div>
    </div>
{% endblock %}

templates/CV/experience_form.html
{% extends 'CV/base.html' %}
{% load crispy_forms_tags %}
{% block info %}
    <h1>Update Experience</h1>
    <div class="jumbotron" style="background-color: white">
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-primary" id="id_save">Save</button>
    </form>
    </div>
{% endblock %}

templates/CV/experience_list.html
{% extends 'CV/base.html' %}
{% block info %}
    {% if user.is_authenticated %}
        <section class="resume-section" id="experience" style="background-color: white">
            <div class="resume-section-content">
                <h2 class="mb-5">Experience</h2>
                <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                <div class="flex-grow-1">
                    <a href="{% url 'experience_create' %}" id="id_create" style="color:#212529;">Add Entry <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-plus-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M8 3.5a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5H4a.5.5 0 0 1 0-1h3.5V4a.5.5 0 0 1 .5-.5z"/>
  <path fill-rule="evenodd" d="M7.5 8a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1H8.5V12a.5.5 0 0 1-1 0V8z"/>
  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    </svg></a>
                </div>
                </div>
                    {% for experience in experience_list %}
                        <a href="{% url 'experience_edit' pk=experience.pk %}" id="id_edit{{experience.pk}}" style="color:#212529;"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                                                                                         <path fill-rule="evenodd" d="M11.293 1.293a1 1 0 0 1 1.414 0l2 2a1 1 0 0 1 0 1.414l-9 9a1 1 0 0 1-.39.242l-3 1a1 1 0 0 1-1.266-1.265l1-3a1 1 0 0 1 .242-.391l9-9zM12 2l2 2-9 9-3 1 1-3 9-9z"/>
                                                                                                                         <path fill-rule="evenodd" d="M12.146 6.354l-2.5-2.5.708-.708 2.5 2.5-.707.708zM3 10v.5a.5.5 0 0 0 .5.5H4v.5a.5.5 0 0 0 .5.5H5v.5a.5.5 0 0 0 .5.5H6v-1.5a.5.5 0 0 0-.5-.5H5v-.5a.5.5 0 0 0-.5-.5H3z"/>
                                                                                                                         </svg></a>
                                                                                                      <a href="{% url 'experience_delete' pk=experience.pk %}" id="id_delete{{experience.pk}}" style="color:#212529;"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-x-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
  <path fill-rule="evenodd" d="M11.854 4.146a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708-.708l7-7a.5.5 0 0 1 .708 0z"/>
  <path fill-rule="evenodd" d="M4.146 4.146a.5.5 0 0 0 0 .708l7 7a.5.5 0 0 0 .708-.708l-7-7a.5.5 0 0 0-.708 0z"/>
</svg></a>
                        <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                            <div class="flex-grow-1">
                        <h3 class="mb-0" id="id_job_title{{experience.pk}}">{{ experience.job_title }}</h3>
                        <div class="subheading mb-3" id="id_job_company">{{ experience.job_company }}</div>
                        <p id="id_job_description">{{ experience.job_description }}</p>

                        </div>
                    <div class="flex-shrink-0"><span class="text-primary" id="id_job_start_date">{{ experience.job_start_date }}</span> - <span class="text-primary" id="id_job_end_date"> {{ experience.job_end_date }}</span></div>
                        </div>

                    {% endfor %}
            </div>
        </section>
        <hr class="m-0" />
    {% else %}

        <section class="resume-section jumbotron" id="experience" style="background-color: white">
            <div class="resume-section-content">
                <h2 class="mb-5">Experience</h2>

                    {% for experience in experience_list %}
                        <div class="d-flex flex-column flex-md-row justify-content-between mb-5">
                    <div class="flex-grow-1">
                        <h3 class="mb-0"><p id="id_job_title">{{ experience.job_title }}</p></h3>
                        <div class="subheading mb-3"><p id="id_job_company">{{ experience.job_company }}</p></div>
                        <p id="id_job_description">{{ experience.job_description }}</p>
                    </div>
                    <div class="flex-shrink-0"><span class="text-primary"><p id="id_job_start_date">{{ experience.job_start_date}}</p> - <p id="id_job_end_date">{{ experience.job_end_date }}</p></span></div>
                    </div>
                    {% endfor %}

            </div>
        </section>
    {% endif %}
{% endblock %}

templates/CV/interests_confirm_delete.html
{% extends 'CV/base.html' %}
{% block info %}
    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4 mt-5">
    <div class="jumbotron jumbotron-fluid" style="background-color: white">
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete the entry for "{{ interests.interests_text }}"?</p>
        <input class='btn btn-danger' type="submit" value="Confirm" id="id_confirm" />
        <a class="nav-link" href="{% url 'interests' %} id="id_confirm>Cancel</a>
    </form>
    </div>
    </div>
{% endblock %}

templates/CV/interests_form.html
{% extends 'CV/base.html' %}
{% load crispy_forms_tags %}
{% block info %}
    <h1>Update Interests</h1>
    <div class="jumbotron" style="background-color: white">
    <form method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="submit" class="save btn btn-primary" id = "id_save">Save</button>
    </form>
    </div>
{% endblock %}

templates/CV/skills_confirm_delete.html
{% extends 'CV/base.html' %}
{% block info %}
    <div class="col-xl-5 col-lg-6 col-md-8 col-sm-10 mx-auto text-center form p-4 mt-5">
    <div class="jumbotron jumbotron-fluid" style="background-color: white">
    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete the entry for "{{ skills.skills_text }}"?</p>
        <input class='btn btn-danger' type="submit" value="Confirm" id="id_confirm"/>
        <a class="nav-link" href="{% url 'skills' %}" id="ic_cancel">Cancel</a>
    </form>
    </div>
    </div>
{% endblock %}